
# NOTICE: Strongly recommended to subsequently add autogenerated annotation to improve Retrieval-Augmented-Generation (RAG) with _semanticAssist .

_knowledge-ubDistBuild() {
    [[ "$objectName" != "ubDistBuild" ]] && _stop 1

    _safeRMR "$scriptLocal"/knowledge/ubDistBuild
    mkdir -p "$scriptLocal"/knowledge/ubDistBuild


    mkdir -p "$scriptLocal"/knowledge/ubDistBuild/_lib/custom
    cp -r "$scriptAbsoluteFolder"/_lib/custom/ubdist_hardening "$scriptLocal"/knowledge/ubDistBuild/_lib/custom/
    cp -r "$scriptAbsoluteFolder"/_lib/custom/ubdist_unattended "$scriptLocal"/knowledge/ubDistBuild/_lib/custom/


    mkdir -p "$scriptLocal"/knowledge/ubDistBuild/_lib
    cp -r "$scriptAbsoluteFolder"/_lib/install "$scriptLocal"/knowledge/ubDistBuild/_lib/
    cp -r "$scriptAbsoluteFolder"/_lib/nsis "$scriptLocal"/knowledge/ubDistBuild/_lib/
    #cp -r "$scriptAbsoluteFolder"/_lib/setup "$scriptLocal"/knowledge/ubDistBuild/_lib/

    mkdir -p "$scriptLocal"/knowledge/ubDistBuild/_lib/setup
    cp -r "$scriptAbsoluteFolder"/_lib/setup/hardware "$scriptLocal"/knowledge/ubDistBuild/_lib/setup/
    cp -r "$scriptAbsoluteFolder"/_lib/setup/nvidia "$scriptLocal"/knowledge/ubDistBuild/_lib/setup/
    cp -r "$scriptAbsoluteFolder"/_lib/setup/rootGrab "$scriptLocal"/knowledge/ubDistBuild/_lib/setup/

    cp -r "$scriptAbsoluteFolder"/_lib/_build-staging-ops.sh "$scriptLocal"/knowledge/ubDistBuild/_lib/

    cp -r "$scriptAbsoluteFolder"/_prog "$scriptLocal"/knowledge/ubDistBuild/
    cp -r "$scriptAbsoluteFolder"/_prog-ops "$scriptLocal"/knowledge/ubDistBuild/

    cp -r "$scriptAbsoluteFolder"/.devops "$scriptLocal"/knowledge/ubDistBuild/
    cp -r "$scriptAbsoluteFolder"/.github "$scriptLocal"/knowledge/ubDistBuild/

    cp -r "$scriptAbsoluteFolder"/ops "$scriptLocal"/knowledge/ubDistBuild/

    cp -r "$scriptAbsoluteFolder"/license-llama "$scriptLocal"/knowledge/ubDistBuild/
    cp "$scriptAbsoluteFolder"/Notice.txt "$scriptLocal"/knowledge/ubDistBuild/
    cp "$scriptAbsoluteFolder"/license.txt "$scriptLocal"/knowledge/ubDistBuild/
    cp "$scriptAbsoluteFolder"/license-installer.txt "$scriptLocal"/knowledge/ubDistBuild/
    cp "$scriptAbsoluteFolder"/agpl-3.0.txt "$scriptLocal"/knowledge/ubDistBuild/

    cp "$scriptAbsoluteFolder"/README.sh.out.txt "$scriptLocal"/knowledge/ubDistBuild/
    cp "$scriptAbsoluteFolder"/README-installer.pdf "$scriptLocal"/knowledge/ubDistBuild/
    cp "$scriptAbsoluteFolder"/README-live.pdf "$scriptLocal"/knowledge/ubDistBuild/
}
